/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.bdavanzadas.bancopresentacion_247283_240005.interfaz;

import javax.swing.JOptionPane;
import org.itson.bdavanzadas.bancodominio_247283_240005.Cliente;
import org.itson.bdavanzadas.bancodominio_247283_240005.Cuenta;
import org.itson.bdavanzadas.bancopersistencia_247283_240005.conexion.Conexion;
import org.itson.bdavanzadas.bancopersistencia_247283_240005.conexion.IConexion;
import org.itson.bdavanzadas.bancopersistencia_247283_240005.daos.ClienteDAO;
import org.itson.bdavanzadas.bancopersistencia_247283_240005.daos.CuentaDAO;
import org.itson.bdavanzadas.bancopersistencia_247283_240005.dto.CuentaDTO;
import org.itson.bdavanzadas.bancopersistencia_247283_240005.persistenciaException.PersistenciaException;

/**
 *
 * @author Chris
 */
public class FrmCuenta extends javax.swing.JFrame {

    String cadenaConexion = "jdbc:mysql://localhost:3306/banco_247283_240005", usuario = "root", contra = "Avenged21@";
    IConexion c = new Conexion(cadenaConexion, usuario, contra);
    CuentaDAO cDAO = new CuentaDAO(c);
    ClienteDAO cliDAO = new ClienteDAO(c);

    /**
     * Creates new form FrmCuenta
     */
    public FrmCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bActualizaCliente = new javax.swing.JButton();
        bAgregarCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bActualizaCliente.setText("Actualiza cliente");
        bActualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizaClienteActionPerformed(evt);
            }
        });

        bAgregarCuenta.setText("Agregar cuenta");
        bAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bActualizaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAgregarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(bAgregarCuenta)
                .addGap(28, 28, 28)
                .addComponent(bActualizaCliente)
                .addGap(152, 152, 152))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizaClienteActionPerformed
        // TODO add your handling code here:
        FrmActualizaCliente f = new FrmActualizaCliente();
        f.setVisible(true);
    }//GEN-LAST:event_bActualizaClienteActionPerformed

    private void bAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarCuentaActionPerformed
        // TODO add your handling code here:
        try {
            String clienteIdStr = JOptionPane.showInputDialog("Ingrese el ID del cliente:");

            if (clienteIdStr == null || clienteIdStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID de cliente no válido");
                return;
            }

            int clienteId = Integer.parseInt(clienteIdStr);

            Cliente cliente = cliDAO.buscarCliente(clienteId);

            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "No se encontró un cliente con el ID proporcionado.");
                return;
            }

            CuentaDTO cuentaDTO = new CuentaDTO();
            cuentaDTO.setCliente(cliente);

            Cuenta cuentaAgregada = cDAO.agregarCuenta(cuentaDTO);

            if (cuentaAgregada != null) {
                JOptionPane.showMessageDialog(this, "Cuenta agregada correctamente con ID: " + cuentaAgregada.getId());

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar la cuenta. Verifica la información.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID de cliente no válido. Ingrese un número válido.");
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error al intentar agregar la cuenta: " + e.getMessage());
        }
    }//GEN-LAST:event_bAgregarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizaCliente;
    private javax.swing.JButton bAgregarCuenta;
    // End of variables declaration//GEN-END:variables
}
